window.MATC_ARTICLES = [
  {
    slug: 'routine-mattina-serena',
    title: 'Routine del mattino: 7 idee semplici per iniziare la giornata senza caos',
    category: 'Lifestyle',
    date: '2026-03-06',
    author: 'Redazione MammeAndTheCity',
    readingTime: '6 min',
    excerpt: 'Piccoli rituali realistici per alleggerire le mattine in famiglia, anche quando il tempo sembra non bastare mai.',
    image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Mamma con tazza di te in una cucina luminosa',
    url: 'articolo-routine-mattina-serena.html',
    featured: true,
    popular: true,
    trending: true
  },
  {
    slug: 'weekend-bambini-citta',
    title: 'Weekend con i bambini in citta: 10 idee pratiche da fare senza stress',
    category: 'Lifestyle',
    date: '2026-03-02',
    author: 'Chiara Bassi',
    readingTime: '5 min',
    excerpt: 'Attivita facili, budget-friendly e adatte a chi vuole vivere la citta con i bambini in modo piu leggero.',
    image: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Famiglia durante una passeggiata urbana nel weekend',
    url: 'articolo-weekend-bambini-citta.html',
    popular: true,
    trending: true
  },
  {
    slug: 'menu-settimanale-famiglia',
    title: 'Menu settimanale facile: come organizzare i pasti in anticipo e cucinare meglio',
    category: 'Cucina',
    date: '2026-03-08',
    author: 'Elisa Moretti',
    readingTime: '7 min',
    excerpt: 'Strategie concrete per pianificare pranzi e cene, ridurre gli sprechi e alleggerire la settimana.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Tavolo con ingredienti e meal prep per la settimana',
    url: 'articolo-menu-settimanale-famiglia.html',
    popular: true,
    trending: true
  },
  {
    slug: 'torta-salata-orto',
    title: 'Torta salata dell orto: ricetta veloce per una cena completa e stagionale',
    category: 'Cucina',
    date: '2026-02-27',
    author: 'Redazione MammeAndTheCity',
    readingTime: '4 min',
    excerpt: 'Una ricetta versatile, semplice da personalizzare e perfetta per usare al meglio le verdure di stagione.',
    image: 'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Torta salata rustica servita su tavolo chiaro',
    url: 'articolo-torta-salata-orto.html',
    popular: false,
    trending: false
  },
  {
    slug: 'orto-balcone-erbe',
    title: 'Orto sul balcone: le erbe aromatiche piu facili da coltivare anche in poco spazio',
    category: 'Giardinaggio',
    date: '2026-03-04',
    author: 'Marta Leone',
    readingTime: '6 min',
    excerpt: 'Basilico, menta, rosmarino e non solo: consigli semplici per partire bene anche con un balcone piccolo.',
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Vasi di erbe aromatiche su balcone soleggiato',
    url: 'articolo-orto-balcone-erbe.html',
    popular: true,
    trending: false
  },
  {
    slug: 'fiori-facili-primavera',
    title: 'Fiori facili di primavera: 6 varieta resistenti per dare colore a terrazzo e giardino',
    category: 'Giardinaggio',
    date: '2026-02-25',
    author: 'Marta Leone',
    readingTime: '5 min',
    excerpt: 'Una selezione di fioriture semplici da gestire, luminose e adatte anche a chi ha poco tempo.',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Fiori colorati in vaso su terrazzo',
    url: 'articolo-fiori-facili-primavera.html',
    popular: false,
    trending: true
  },
  {
    slug: 'ingresso-ordinato-casa',
    title: 'Ingresso di casa ordinato: 5 soluzioni salvaspazio che migliorano subito la routine',
    category: 'Casa',
    date: '2026-03-01',
    author: 'Silvia Conti',
    readingTime: '5 min',
    excerpt: 'Piccoli interventi che aiutano a gestire giacche, scarpe, zaini e oggetti quotidiani con piu ordine.',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Ingresso di casa luminoso e ben organizzato',
    url: 'articolo-ingresso-ordinato-casa.html',
    popular: true,
    trending: false
  },
  {
    slug: 'bucato-profumato-naturale',
    title: 'Bucato profumato in modo naturale: trucchi semplici per capi freschi piu a lungo',
    category: 'Casa',
    date: '2026-02-22',
    author: 'Silvia Conti',
    readingTime: '4 min',
    excerpt: 'Metodi pratici e delicati per migliorare il profumo del bucato senza appesantire tessuti e ambiente.',
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=1200&h=800&q=80',
    alt: 'Biancheria pulita e piegata in ambiente luminoso',
    url: 'articolo-bucato-profumato-naturale.html',
    popular: false,
    trending: true
  }
];
